name: tasknow_release
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  google_fonts: ^5.0.0
  url_launcher: ^6.0.10
  sqflite: ^2.0.0
  path_provider: ^2.0.2
 
   
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.0.1
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/1.png
  - assets/+.png
  - assets/set.png
  - assets/strelka.png
  - assets/x.png
  - assets/gt.png
  - assets/ins.png
  - assets/tg.png
  - assets/line.png

